// Autogenerated from Pigeon (v22.6.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class Mymessage;
@class NotificationData;
@class CustomNumber;

@interface Mymessage : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithTitle:(NSString *)title
    body:(NSString *)body
    email:(NSString *)email;
@property(nonatomic, copy) NSString * title;
@property(nonatomic, copy) NSString * body;
@property(nonatomic, copy) NSString * email;
@end

@interface NotificationData : NSObject
+ (instancetype)makeWithId:(nullable NSString *)id
    name:(nullable NSString *)name
    description:(nullable NSString *)description;
@property(nonatomic, copy, nullable) NSString * id;
@property(nonatomic, copy, nullable) NSString * name;
@property(nonatomic, copy, nullable) NSString * description;
@end

@interface CustomNumber : NSObject
+ (instancetype)makeWithNumber:(nullable NSNumber *)number;
@property(nonatomic, strong, nullable) NSNumber * number;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *nullGetPigeonCodec(void);

@protocol MessageApi
/// @return `nil` only when `error != nil`.
- (nullable NSArray<Mymessage *> *)getMessageFromemail:(NSString *)fromemail error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpMessageApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<MessageApi> *_Nullable api);

extern void SetUpMessageApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<MessageApi> *_Nullable api, NSString *messageChannelSuffix);


@protocol NotificationApi
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)createNotificationChannelData:(NotificationData *)data error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)openFileFilePath:(NSString *)filePath error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpNotificationApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<NotificationApi> *_Nullable api);

extern void SetUpNotificationApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<NotificationApi> *_Nullable api, NSString *messageChannelSuffix);


@protocol NumberApi
/// @return `nil` only when `error != nil`.
- (nullable CustomNumber *)getNumberWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpNumberApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<NumberApi> *_Nullable api);

extern void SetUpNumberApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<NumberApi> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
